In [1]:
import nltk

In [2]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\santo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [3]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [4]:
text = "Tell them the North remembers. Tell them winter came for House Frey."

In [6]:
words = word_tokenize(text)
sentences = sent_tokenize(text)


LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\santo/nltk_data'
    - 'c:\\Users\\santo\\AppData\\Local\\Programs\\Python\\Python312\\nltk_data'
    - 'c:\\Users\\santo\\AppData\\Local\\Programs\\Python\\Python312\\share\\nltk_data'
    - 'c:\\Users\\santo\\AppData\\Local\\Programs\\Python\\Python312\\lib\\nltk_data'
    - 'C:\\Users\\santo\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


In [ ]:
print ("Word_tokenize:",words)
print ("Sentence_tokenize:",sentences)

In [ ]:
import string
text = "hello world! How are you today?"

In [ ]:
translator=str.maketrans('','',string.punctuation)
cleaned_text=text.translate(translator)
print(cleaned_text)

hello world How are you today


In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
text = "Tell them the North"
words=word_tokenize(text.lower())
stop_words=set(stopwords.words('english'))
flitered_words=set(

#26/08/2026

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ['The quick brown fox jumps over the lazy dog.', 'The dog barks at the cat.', 'The cat chases the mouse.']
vectorizer = CountVectorizer()
x=vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())
print(x.toarray())


['at' 'barks' 'brown' 'cat' 'chases' 'dog' 'fox' 'jumps' 'lazy' 'mouse'
 'over' 'quick' 'the']
[[0 0 1 0 0 1 1 1 1 0 1 1 2]
 [1 1 0 1 0 1 0 0 0 0 0 0 2]
 [0 0 0 1 1 0 0 0 0 1 0 0 2]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = ['The quick brown fox jumps over the lazy dog.', 'The dog barks at the cat.', 'The cat chases the mouse.']
vectorizer = TfidfVectorizer()
x=vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())
print(x.toarray())


['at' 'barks' 'brown' 'cat' 'chases' 'dog' 'fox' 'jumps' 'lazy' 'mouse'
 'over' 'quick' 'the']
[[0.         0.         0.35413578 0.         0.         0.26932939
  0.35413578 0.35413578 0.35413578 0.         0.35413578 0.35413578
  0.41831659]
 [0.46869865 0.46869865 0.         0.3564574  0.         0.3564574
  0.         0.         0.         0.         0.         0.
  0.55364194]
 [0.         0.         0.         0.38151877 0.50165133 0.
  0.         0.         0.         0.50165133 0.         0.
  0.59256672]]


#2/9/2024

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize,sent_tokenize
from sklearn.metrics import accuracy_score
import string
import pandas as pd


In [ ]:
data{'text';["Ilove this movie ".]}

In [ ]:
df['text']=df['text'].apply(preprocess)